spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
      database-platform=org:
                hibernate:
                  dialect:
                    PostgreSQLDialect